global using IAuthenticationService = NSE.WebApp.MVC.Services.IAuthenticationService;
global using AuthenticationService = NSE.WebApp.MVC.Services.AuthenticationService;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Localization;
global using NSE.WebApp.MVC.Services.Handlers;
global using System.IdentityModel.Tokens.Jwt;
global using Microsoft.AspNetCore.Mvc.Razor;
global using NSE.WebApp.MVC.Configuration;
global using System.Security.Cryptography;
global using System.Runtime.Serialization;
global using Microsoft.Extensions.Options;
global using NSE.WebApp.MVC.Extensions;
global using Microsoft.AspNetCore.Mvc;
global using NSE.WebApp.MVC.Services;
global using System.Net.Http.Headers;
global using System.Security.Claims;
global using NSE.WebApp.MVC.Models;
global using Polly.Extensions.Http;
global using System.ComponentModel;
global using Polly.CircuitBreaker;
global using System.Globalization;
global using System.Text.Json;
global using System.Text;
global using System.Net;
global using Polly;