global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation.Results;
global using System.Threading.Tasks;
global using NSE.Orders.Domain;
global using NSE.Core.Mediator;
global using NSE.Core.Messages;
global using NSE.Core.Data;
global using System.Linq;
